/** What Nox Code knows about file kinds: color, badge text and a glyph. */

export interface FileKind {
  /** Brand-ish color of the language / format. */
  color: string;
  /** Two-three letter badge ("TS", "{}"). */
  badge: string;
  /** Text color on the badge. */
  badgeFg?: string;
  /** Icon name from ICON_LIBRARY. */
  icon: string;
}

const k = (color: string, badge: string, icon: string, badgeFg?: string): FileKind => ({ color, badge, icon, badgeFg });

export const BY_EXT: Record<string, FileKind> = {
  ts: k("#3178c6", "TS", "FileCode"),
  mts: k("#3178c6", "TS", "FileCode"),
  cts: k("#3178c6", "TS", "FileCode"),
  tsx: k("#3b9ae1", "TSX", "Atom"),
  js: k("#f1d22e", "JS", "FileCode", "#1f1f1f"),
  mjs: k("#f1d22e", "JS", "FileCode", "#1f1f1f"),
  cjs: k("#f1d22e", "JS", "FileCode", "#1f1f1f"),
  jsx: k("#61dafb", "JSX", "Atom", "#1f1f1f"),
  json: k("#cbcb41", "{}", "Braces", "#1f1f1f"),
  jsonc: k("#cbcb41", "{}", "Braces", "#1f1f1f"),
  json5: k("#cbcb41", "{}", "Braces", "#1f1f1f"),
  md: k("#519aba", "MD", "BookOpen"),
  mdx: k("#f9ac00", "MDX", "BookOpen", "#1f1f1f"),
  txt: k("#9aa0a6", "TXT", "FileText"),
  rs: k("#dea584", "RS", "Cog", "#1f1f1f"),
  py: k("#3776ab", "PY", "FileCode"),
  pyi: k("#3776ab", "PY", "FileCode"),
  ipynb: k("#f37626", "NB", "Book"),
  go: k("#00add8", "GO", "FileCode"),
  java: k("#e76f00", "JV", "Coffee"),
  kt: k("#a97bff", "KT", "FileCode"),
  kts: k("#a97bff", "KT", "FileCode"),
  swift: k("#f05138", "SW", "Bird"),
  c: k("#5c8dbc", "C", "FileCode"),
  h: k("#a074c4", "H", "FileCode"),
  cpp: k("#f34b7d", "C++", "FileCode"),
  cc: k("#f34b7d", "C++", "FileCode"),
  cxx: k("#f34b7d", "C++", "FileCode"),
  hpp: k("#a074c4", "H++", "FileCode"),
  cs: k("#9b4dca", "C#", "Hash"),
  csx: k("#9b4dca", "C#", "Hash"),
  csproj: k("#9b4dca", "PRJ", "Boxes"),
  sln: k("#9b4dca", "SLN", "Boxes"),
  razor: k("#5c2d91", "RZ", "CodeXml"),
  cshtml: k("#5c2d91", "RZ", "CodeXml"),
  fs: k("#378bba", "F#", "Hash"),
  vb: k("#945db7", "VB", "FileCode"),
  rb: k("#cc342d", "RB", "Gem"),
  php: k("#777bb4", "PHP", "FileCode"),
  lua: k("#51a0cf", "LUA", "Moon"),
  dart: k("#00b4ab", "DT", "Target"),
  vue: k("#41b883", "V", "Triangle"),
  svelte: k("#ff3e00", "S", "Flame"),
  html: k("#e34c26", "<>", "CodeXml"),
  htm: k("#e34c26", "<>", "CodeXml"),
  css: k("#663399", "#", "Hash"),
  scss: k("#c6538c", "#", "Hash"),
  sass: k("#c6538c", "#", "Hash"),
  less: k("#1d365d", "#", "Hash"),
  xml: k("#f1662a", "<>", "CodeXml"),
  svg: k("#ffb13b", "SVG", "Shapes", "#1f1f1f"),
  yaml: k("#cb171e", "YML", "ListTree"),
  yml: k("#cb171e", "YML", "ListTree"),
  toml: k("#9c4221", "TML", "Settings2"),
  ini: k("#6d8086", "INI", "Settings2"),
  cfg: k("#6d8086", "CFG", "Settings2"),
  conf: k("#6d8086", "CFG", "Settings2"),
  env: k("#ecd53f", "ENV", "Key", "#1f1f1f"),
  sql: k("#e38c00", "SQL", "Database"),
  db: k("#e38c00", "DB", "Database"),
  sqlite: k("#e38c00", "DB", "Database"),
  sh: k("#4eaa25", "$", "SquareTerminal"),
  bash: k("#4eaa25", "$", "SquareTerminal"),
  zsh: k("#4eaa25", "$", "SquareTerminal"),
  fish: k("#4eaa25", "$", "SquareTerminal"),
  ps1: k("#2d7dd2", "PS", "Terminal"),
  psm1: k("#2d7dd2", "PS", "Terminal"),
  bat: k("#c1f12e", "BAT", "Terminal", "#1f1f1f"),
  cmd: k("#c1f12e", "CMD", "Terminal", "#1f1f1f"),
  png: k("#a074c4", "IMG", "Image"),
  jpg: k("#a074c4", "IMG", "Image"),
  jpeg: k("#a074c4", "IMG", "Image"),
  gif: k("#a074c4", "GIF", "Image"),
  webp: k("#a074c4", "IMG", "Image"),
  ico: k("#a074c4", "ICO", "Image"),
  bmp: k("#a074c4", "IMG", "Image"),
  avif: k("#a074c4", "IMG", "Image"),
  mp4: k("#fd971f", "VID", "Film"),
  mov: k("#fd971f", "VID", "Film"),
  webm: k("#fd971f", "VID", "Film"),
  mp3: k("#e91e63", "AUD", "Music"),
  wav: k("#e91e63", "AUD", "Music"),
  flac: k("#e91e63", "AUD", "Music"),
  zip: k("#8a8a8a", "ZIP", "FileArchive"),
  gz: k("#8a8a8a", "GZ", "FileArchive"),
  tar: k("#8a8a8a", "TAR", "FileArchive"),
  "7z": k("#8a8a8a", "7Z", "FileArchive"),
  rar: k("#8a8a8a", "RAR", "FileArchive"),
  pdf: k("#e5252a", "PDF", "FileText"),
  csv: k("#89e051", "CSV", "Table", "#1f1f1f"),
  tsv: k("#89e051", "TSV", "Table", "#1f1f1f"),
  xlsx: k("#1d6f42", "XLS", "FileSpreadsheet"),
  lock: k("#8a8a8a", "LK", "Lock"),
  log: k("#8a8a8a", "LOG", "List"),
  diff: k("#41b883", "±", "Diff"),
  patch: k("#41b883", "±", "Diff"),
  graphql: k("#e10098", "GQL", "Workflow"),
  gql: k("#e10098", "GQL", "Workflow"),
  proto: k("#4285f4", "PB", "Blocks"),
  wasm: k("#654ff0", "WA", "Binary"),
  exe: k("#8a8a8a", "EXE", "AppWindow"),
  dll: k("#8a8a8a", "DLL", "Binary"),
  ttf: k("#d4d4d4", "Aa", "Type", "#1f1f1f"),
  otf: k("#d4d4d4", "Aa", "Type", "#1f1f1f"),
  woff: k("#d4d4d4", "Aa", "Type", "#1f1f1f"),
  woff2: k("#d4d4d4", "Aa", "Type", "#1f1f1f"),
  pem: k("#e8b339", "KEY", "Key", "#1f1f1f"),
  key: k("#e8b339", "KEY", "Key", "#1f1f1f"),
  crt: k("#e8b339", "CRT", "ShieldCheck", "#1f1f1f"),
  sol: k("#8a8a8a", "SOL", "Diamond"),
  zig: k("#f7a41d", "ZIG", "Zap", "#1f1f1f"),
  ex: k("#6e4a7e", "EX", "Droplet"),
  exs: k("#6e4a7e", "EX", "Droplet"),
  erl: k("#a90533", "ERL", "FileCode"),
  hs: k("#5e5086", "HS", "Sigma"),
  scala: k("#dc322f", "SC", "Layers"),
  clj: k("#63b132", "CLJ", "FileCode"),
  r: k("#276dc3", "R", "Sigma"),
  jl: k("#9558b2", "JL", "Circle"),
  tf: k("#7b42bc", "TF", "Boxes"),
  nix: k("#7ebae4", "NIX", "Snowflake", "#1f1f1f"),
};

export const BY_NAME: Record<string, FileKind> = {
  "package.json": k("#cb3837", "NPM", "Package"),
  "package-lock.json": k("#cb3837", "NPM", "Lock"),
  "pnpm-lock.yaml": k("#f69220", "PN", "Lock", "#1f1f1f"),
  "yarn.lock": k("#2c8ebb", "YN", "Lock"),
  "bun.lockb": k("#fbf0df", "BUN", "Lock", "#1f1f1f"),
  "tsconfig.json": k("#3178c6", "TS", "Settings"),
  "jsconfig.json": k("#f1d22e", "JS", "Settings", "#1f1f1f"),
  "cargo.toml": k("#dea584", "RS", "Package", "#1f1f1f"),
  "cargo.lock": k("#dea584", "RS", "Lock", "#1f1f1f"),
  "go.mod": k("#00add8", "GO", "Package"),
  "go.sum": k("#00add8", "GO", "Lock"),
  dockerfile: k("#2496ed", "DK", "Container"),
  "docker-compose.yml": k("#2496ed", "DK", "Container"),
  "docker-compose.yaml": k("#2496ed", "DK", "Container"),
  makefile: k("#6d8086", "MK", "Hammer"),
  "cmakelists.txt": k("#064f8c", "CM", "Hammer"),
  ".gitignore": k("#f14e32", "GIT", "GitBranch"),
  ".gitattributes": k("#f14e32", "GIT", "GitBranch"),
  ".gitmodules": k("#f14e32", "GIT", "GitBranch"),
  ".editorconfig": k("#8a8a8a", "EC", "Settings2"),
  ".prettierrc": k("#c596c7", "PR", "Paintbrush"),
  ".prettierrc.json": k("#c596c7", "PR", "Paintbrush"),
  "prettier.config.js": k("#c596c7", "PR", "Paintbrush"),
  ".eslintrc": k("#4b32c3", "ES", "ShieldCheck"),
  ".eslintrc.json": k("#4b32c3", "ES", "ShieldCheck"),
  "eslint.config.js": k("#4b32c3", "ES", "ShieldCheck"),
  "vite.config.ts": k("#bd34fe", "VI", "Zap"),
  "vite.config.js": k("#bd34fe", "VI", "Zap"),
  "vitest.config.ts": k("#729b1b", "VT", "TestTube"),
  "playwright.config.ts": k("#2ead33", "PW", "TestTube"),
  "tailwind.config.js": k("#38bdf8", "TW", "Wind", "#1f1f1f"),
  "tailwind.config.ts": k("#38bdf8", "TW", "Wind", "#1f1f1f"),
  "tauri.conf.json": k("#ffc131", "TA", "Settings", "#1f1f1f"),
  "readme.md": k("#519aba", "i", "BookOpen"),
  "changelog.md": k("#519aba", "CL", "Clock"),
  license: k("#d4b106", "LIC", "Scale", "#1f1f1f"),
  "license.md": k("#d4b106", "LIC", "Scale", "#1f1f1f"),
  "license.txt": k("#d4b106", "LIC", "Scale", "#1f1f1f"),
  ".env": k("#ecd53f", "ENV", "Key", "#1f1f1f"),
  ".env.local": k("#ecd53f", "ENV", "Key", "#1f1f1f"),
  ".env.example": k("#ecd53f", "ENV", "Key", "#1f1f1f"),
  ".npmrc": k("#cb3837", "NPM", "Settings2"),
  ".nvmrc": k("#3c873a", "NV", "Settings2"),
  "requirements.txt": k("#3776ab", "PY", "List"),
  "pyproject.toml": k("#3776ab", "PY", "Package"),
  "gemfile": k("#cc342d", "RB", "Gem"),
  "index.html": k("#e34c26", "<>", "Globe"),
  favicon: k("#a074c4", "IMG", "Star"),
};

export interface FolderKind {
  color: string;
  icon: string;
  iconOpen?: string;
}

const f = (color: string, icon: string, iconOpen?: string): FolderKind => ({ color, icon, iconOpen });

export const FOLDERS: Record<string, FolderKind> = {
  src: f("#4fc1ff", "FolderCode"),
  source: f("#4fc1ff", "FolderCode"),
  lib: f("#4fc1ff", "FolderCode"),
  app: f("#4fc1ff", "FolderCode"),
  components: f("#c586c0", "FolderKanban"),
  ui: f("#c586c0", "FolderKanban"),
  pages: f("#c586c0", "FolderKanban"),
  views: f("#c586c0", "FolderKanban"),
  layout: f("#c586c0", "FolderKanban"),
  hooks: f("#61dafb", "FolderCode"),
  utils: f("#8bc34a", "FolderCog"),
  helpers: f("#8bc34a", "FolderCog"),
  scripts: f("#8bc34a", "FolderCog"),
  tools: f("#8bc34a", "FolderCog"),
  config: f("#8bc34a", "FolderCog"),
  ".vscode": f("#3794ff", "FolderCog"),
  ".claude": f("#d97757", "FolderCog"),
  ".github": f("#a0a0a0", "FolderGit2"),
  ".git": f("#f14e32", "FolderGit2"),
  node_modules: f("#8a8a8a", "FolderArchive"),
  vendor: f("#8a8a8a", "FolderArchive"),
  target: f("#8a8a8a", "FolderOutput"),
  dist: f("#8a8a8a", "FolderOutput"),
  build: f("#8a8a8a", "FolderOutput"),
  out: f("#8a8a8a", "FolderOutput"),
  public: f("#ffca28", "FolderRoot"),
  static: f("#ffca28", "FolderRoot"),
  assets: f("#ffca28", "FolderHeart"),
  images: f("#ffca28", "FolderHeart"),
  img: f("#ffca28", "FolderHeart"),
  icons: f("#ffca28", "FolderHeart"),
  fonts: f("#ffca28", "FolderHeart"),
  styles: f("#ec407a", "FolderHeart"),
  css: f("#ec407a", "FolderHeart"),
  test: f("#66bb6a", "FolderSearch"),
  tests: f("#66bb6a", "FolderSearch"),
  __tests__: f("#66bb6a", "FolderSearch"),
  e2e: f("#66bb6a", "FolderSearch"),
  spec: f("#66bb6a", "FolderSearch"),
  docs: f("#42a5f5", "FolderTree"),
  doc: f("#42a5f5", "FolderTree"),
  data: f("#ffb74d", "FolderInput"),
  db: f("#ffb74d", "FolderInput"),
  migrations: f("#ffb74d", "FolderInput"),
  keys: f("#e8b339", "FolderKey"),
  secrets: f("#e8b339", "FolderLock"),
  "src-tauri": f("#ffc131", "FolderCog"),
  crates: f("#dea584", "FolderCode"),
  store: f("#7e57c2", "FolderInput"),
  stores: f("#7e57c2", "FolderInput"),
  themes: f("#ec407a", "FolderHeart"),
  extensions: f("#26a69a", "FolderKanban"),
  i18n: f("#26a69a", "FolderTree"),
  locales: f("#26a69a", "FolderTree"),
};

export const DEFAULT_FOLDER_COLOR = "#dcb67a";

export function extOf(name: string): string {
  const lower = name.toLowerCase();
  const i = lower.lastIndexOf(".");
  return i > 0 ? lower.slice(i + 1) : lower.startsWith(".") ? lower.slice(1) : "";
}

export function fileKind(name: string): FileKind | null {
  const lower = name.toLowerCase();
  if (BY_NAME[lower]) return BY_NAME[lower];
  if (lower.startsWith(".env")) return BY_NAME[".env"];
  if (lower.startsWith("dockerfile")) return BY_NAME.dockerfile;
  if (/\.(test|spec)\.[jt]sx?$/.test(lower)) return k("#66bb6a", "TST", "TestTube");
  if (lower.endsWith(".d.ts")) return k("#3178c6", "DTS", "FileType");
  const ext = extOf(name);
  return BY_EXT[ext] ?? null;
}
